// Constantes pour les touches
KRight               : x
KLeft                : w
KShoot               :   

//  Constantes liées à l envahisseur
KInvadersColor    : KJaune
KInsideInvader       : W
KMissile             : T
KBegInvader    : 0
KInvadersSize      : 5
KMissileRatio    : 2

// Constantes liées au joueur
KInsideMe            : A
KTorpedo             : |
KMyColor             : KRouge
KMyLife              : 4
KRatioMeInvaders     : 4
KBegMe               : 5

// Constantes liées à l'eapace  de jeu (l'écran)
KSizeLine      : 10
KSizeSpace     : 10
KEmpty               : 

// Constantes liées au fonctionalité
KBonus              : B
KRatio              : 60
KMur                : #

// Adresse des ressources audio en ligne ou sur le PC (pour un fichier present du le PC le format est ( files:///ADRESSE_VERS_LE_FICHIERS )
KIntroSound          : http://66.90.91.26/ost/pokemon-gold-silver/mztvvniogc/22-trainer-battle-theme-1.mp3
KHistoSound          : http://66.90.91.26/ost/pokemon-gold-silver/jsoxvamhwr/13-route-29.mp3
KGameSound           : http://66.90.91.26/ost/splatoon-gamerip-/dzokvigbrs/008-tutorial-theme-5th-section-.mp3
KGameOverSound       : http://66.90.91.26/ost/splatoon-gamerip-/rfpqkvsqff/022-defeat-theme.mp3
KEndSound            : http://66.90.91.26/ost/splatoon-gamerip-/pzxjtrmeum/040-main-theme-unofficial-medley-by-nintenroy-.mp3